import type { FormEvent, ReactNode } from 'react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

export function Login() { const { signIn } = useAuth(); const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); const result = await signIn(email.trim(), password); if (result.error) setError(result.error.message); else navigate('/dashboard'); setBusy(false); }; return <AuthFrame title="Welcome back" subtitle="Sign in to your CandidFan account."><form onSubmit={(event) => void submit(event)} className="space-y-5"><div><Label htmlFor="email">Email</Label><Input id="email" type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2" /></div><div><div className="flex justify-between"><Label htmlFor="password">Password</Label><Link className="text-xs text-violet-300 hover:underline" to="/forgot-password">Forgot password?</Link></div><Input id="password" type="password" required value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2" /></div>{error && <p className="text-sm text-rose-300">{error}</p>}<Button className="w-full bg-gradient-to-r from-violet-600 to-sky-600" disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</Button><p className="text-center text-sm text-slate-400">New here? <Link className="text-violet-300" to="/signup">Create an account</Link></p></form></AuthFrame>; }
export function AuthFrame({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <div className="container mx-auto flex min-h-[70vh] max-w-md items-center px-4 py-12"><Card className="w-full border-white/10 bg-white/[0.05] text-white"><CardHeader><CardTitle className="text-2xl">{title}</CardTitle><p className="text-sm text-slate-400">{subtitle}</p></CardHeader><CardContent>{children}</CardContent></Card></div>; }
