import type { FormEvent } from 'react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { AuthFrame } from './Login';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

export function Signup() { const { signUp } = useAuth(); const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); if (password.length < 8 || password !== confirm) { setError(password.length < 8 ? 'Use at least 8 characters.' : 'Passwords do not match.'); return; } setBusy(true); setError(''); const result = await signUp(email.trim(), password); if (result.error) setError(result.error.message); else navigate(`/verify-email?email=${encodeURIComponent(email.trim())}`); setBusy(false); }; return <AuthFrame title="Join CandidFan" subtitle="Create an account to unlock lifetime access."><form onSubmit={(event) => void submit(event)} className="space-y-5"><div><Label htmlFor="email">Email</Label><Input id="email" type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2" /></div><div><Label htmlFor="password">Password</Label><Input id="password" type="password" minLength={8} required value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2" /></div><div><Label htmlFor="confirm">Confirm password</Label><Input id="confirm" type="password" minLength={8} required value={confirm} onChange={(e) => setConfirm(e.target.value)} className="mt-2" /></div>{error && <p className="text-sm text-rose-300">{error}</p>}<Button className="w-full bg-gradient-to-r from-violet-600 to-sky-600" disabled={busy}>{busy ? 'Creating account…' : 'Create account'}</Button><p className="text-center text-sm text-slate-400">Already registered? <Link className="text-violet-300" to="/login">Sign in</Link></p></form></AuthFrame>; }
