import type { FormEvent } from 'react';
import { useState } from 'react';
import { Link, useSearchParams, useNavigate } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { AuthFrame } from './Login';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

export function VerifyEmail() { const [params] = useSearchParams(); const navigate = useNavigate(); const { verifyEmailCode, resendVerificationCode } = useAuth(); const [email, setEmail] = useState(params.get('email') || ''); const [token, setToken] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); const result = await verifyEmailCode(email.trim(), token.trim()); if (result.error) setError(result.error.message); else navigate('/dashboard'); }; const resend = async () => { const result = await resendVerificationCode(email.trim()); setMessage(result.error ? result.error.message : 'A new code is on its way.'); }; return <AuthFrame title="Verify your email" subtitle="Enter the code from Supabase Auth to finish signing up."><form onSubmit={(event) => void submit(event)} className="space-y-5"><div><Label htmlFor="email">Email</Label><Input id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required className="mt-2" /></div><div><Label htmlFor="token">Verification code</Label><Input id="token" inputMode="numeric" maxLength={6} value={token} onChange={(e) => setToken(e.target.value.replace(/\D/g, ''))} required className="mt-2 tracking-[0.4em]" /></div>{error && <p className="text-sm text-rose-300">{error}</p>}{message && <p className="text-sm text-emerald-300">{message}</p>}<Button className="w-full bg-gradient-to-r from-violet-600 to-sky-600">Verify email</Button><Button type="button" variant="ghost" className="w-full text-slate-300" onClick={() => void resend()}>Resend code</Button><p className="text-center text-sm text-slate-400"><Link className="text-violet-300" to="/login">Back to sign in</Link></p></form></AuthFrame>; }
