import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Crown, LogOut, Menu, Shield, Sparkles, User, X } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { Button } from './ui/button';

export function Navbar() {
  const { user, isAuthenticated, isAdmin, signOut } = useAuth();
  const [open, setOpen] = useState(false);
  return <nav className="sticky top-0 z-50 border-b border-white/10 bg-slate-950/85 backdrop-blur-xl"><div className="container mx-auto px-4"><div className="h-16 flex items-center justify-between gap-4"><Link to="/" className="font-black text-xl tracking-tight bg-gradient-to-r from-fuchsia-300 via-violet-300 to-sky-300 bg-clip-text text-transparent">CandidFan</Link><div className="hidden md:flex items-center gap-2"><Link to="/"><Button variant="ghost" className="text-slate-300">Browse</Button></Link>{isAuthenticated && <Link to="/support"><Button variant="ghost" className="text-slate-300">Support</Button></Link>}{isAdmin && <Link to="/admin"><Button variant="ghost" className="text-slate-300"><Shield className="mr-2 h-4 w-4" />Admin</Button></Link>}</div><div className="flex items-center gap-2">{isAuthenticated ? <><span className="hidden sm:flex items-center gap-1 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs text-slate-300">{user?.membership_status === 'premium' ? <><Crown className="h-3.5 w-3.5 text-amber-300" />Premium</> : <><Sparkles className="h-3.5 w-3.5 text-violet-300" />{user?.membership_status}</>}</span><Link className="hidden md:block" to="/dashboard"><Button variant="ghost" size="sm" className="text-slate-300"><User className="mr-2 h-4 w-4" />Dashboard</Button></Link><Button variant="ghost" size="sm" className="hidden md:flex text-slate-300" onClick={() => void signOut()}><LogOut className="mr-2 h-4 w-4" />Log out</Button><Button variant="ghost" size="icon" className="md:hidden text-slate-300" onClick={() => setOpen(!open)} aria-label="Open menu">{open ? <X /> : <Menu />}</Button></> : <><Link to="/login"><Button variant="ghost" className="text-slate-300">Log in</Button></Link><Link to="/signup"><Button className="bg-gradient-to-r from-violet-600 to-sky-600"><Sparkles className="mr-2 h-4 w-4" />Join</Button></Link></>}</div></div>{open && <div className="md:hidden border-t border-white/10 py-3 space-y-2"><Link onClick={() => setOpen(false)} className="block" to="/dashboard"><Button variant="ghost" className="w-full justify-start text-slate-300">Dashboard</Button></Link><Link onClick={() => setOpen(false)} className="block" to="/support"><Button variant="ghost" className="w-full justify-start text-slate-300">Support</Button></Link>{isAdmin && <Link onClick={() => setOpen(false)} className="block" to="/admin"><Button variant="ghost" className="w-full justify-start text-slate-300">Admin</Button></Link>}<Button variant="ghost" className="w-full justify-start text-slate-300" onClick={() => { setOpen(false); void signOut(); }}><LogOut className="mr-2 h-4 w-4" />Log out</Button></div>}</div></nav>;
}
